// File generated by FlutterFire CLI. Ignore stub warning in CI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS is not configured');
      case TargetPlatform.windows:
        return web;
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5HDcptF9kHIwPRVnqezF0QjA9-hcBOSw',
    appId: '1:768083696940:android:0129c04e30b2445c172089',
    messagingSenderId: '768083696940',
    projectId: 'wedding-planner-615bc',
    storageBucket: 'wedding-planner-615bc.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5dTf6gjhenF0YsO3cRhk9xpgwSFNIutI',
    appId: '1:768083696940:web:2b9deb03ab344a1c172089',
    messagingSenderId: '768083696940',
    projectId: 'wedding-planner-615bc',
    authDomain: 'wedding-planner-615bc.firebaseapp.com',
    storageBucket: 'wedding-planner-615bc.firebasestorage.app',
    measurementId: 'G-WMYSBD2L5X',
  );
}
