// File generated by FlutterFire CLI. Ignore stub warning in CI
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError('Web is not configured');
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError('iOS is not configured');
      default:
        throw UnsupportedError('Unsupported platform');
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5HDcptF9kHIwPRVnqezF0QjA9-hcBOSw',
    appId: '1:768083696940:android:0129c04e30b2445c172089',
    messagingSenderId: '768083696940',
    projectId: 'wedding-planner-615bc',
    storageBucket: 'wedding-planner-615bc.firebasestorage.app',
  );
}
